services:
  postgres:
    image: postgres:alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - pgcaddie:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caddie_app
    ports:
      - '5432:5432'
    networks:
      - backend

  backend:
    build:
      context: ./
      dockerfile: ./docker/app/prod/Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - caddie_network
      - backend

networks:
  caddie_network:
    external: true
  backend:

volumes:
  pgcaddie:
