# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caddie_app
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./
      dockerfile: ./docker/app/local/Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3001:3001' # Nest
      - '9229:9229' # Debug
    depends_on:
      - postgres
    working_dir: /app
    command: ['npm', 'run', 'start:dev']
    user: 0:0
    env_file:
      - .env