services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caddie_app
    ports:
      - '5432:5432'
    networks:
      - backend

  backend:
    build:
      context: ./
      dockerfile: ./docker/app/local/Dockerfile
    volumes:
      - '.:/app'
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      # - /app/node_modules
    ports:
      - '3001:3001' # Nest
      - '9229:9229' # Debug
    depends_on:
      - postgres
    working_dir: /app
    command: ['npm', 'run', 'start:dev']
    user: 0:0
    env_file:
      - .env
    networks:
      - caddie_network
      - backend

networks:
  caddie_network:
    external: true
  backend: