### USER

### find users

GET {{BASE_URL}}/users HTTP/1.1

### create a user

POST {{BASE_URL}}/users HTTP/1.1
content-type: application/json

{
  "email": "toto@toto.com",
  "name": "string",
  "password": "ALongPassw0rdOf30Characters_%/"
}

### find a user by id

GET {{BASE_URL}}/users/d82a8316-f14e-41d0-9c37-62c4bdcb3168 HTTP/1.1


### AUTHENTICATION

### login
POST {{BASE_URL}}/authentication/login HTTP/1.1
content-type: application/json

{
  "email": "toto@toto.com",
  "password": "ALongPassw0rdOf30Characters_%/"
}


### logout

GET {{BASE_URL}}/authentication/logout HTTP/1.1
