/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType, Selectable, Generated } from 'kysely';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Item {
  id: Generated<string>;
  isInCart: boolean;
  listId: string;
  name: string;
}

export interface List {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  title: string;
  updatedAt: Timestamp;
}

export interface Subscriber {
  id: Generated<string>;
  listId: string;
  name: string;
  userId: string;
}

export interface User {
  email: string;
  id: Generated<string>;
  name: string;
  password: string;
}

export interface DB {
  Item: Item;
  List: List;
  Subscriber: Subscriber;
  User: User;
}

/** Row types (selected from DB); use these for return types and DTOs. */
export type UserRow = Selectable<User>;
export type ListRow = Selectable<List>;
export type ItemRow = Selectable<Item>;
export type SubscriberRow = Selectable<Subscriber>;
