/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { Generated, Selectable, Timestamp } from 'kysely';

export type ItemRow = Selectable<Item>;
export type ItemTypeRow = Selectable<ItemType>;
export type ListRow = Selectable<List>;
export type SubscriberRow = Selectable<Subscriber>;
export type UserRow = Selectable<User>;

export interface Item {
  id: Generated<string>;
  isInCart: Generated<boolean>;
  itemTypeId: string | null;
  listId: string;
  name: string;
  quantity: Generated<number>;
}

export interface ItemType {
  id: Generated<string>;
  label: string;
  userId: string;
}

export interface List {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Subscriber {
  id: Generated<string>;
  listId: string;
  name: string;
  userId: string;
}

export interface User {
  email: string;
  id: Generated<string>;
  name: string;
  password: string;
}

export interface DB {
  Item: Item;
  ItemType: ItemType;
  List: List;
  Subscriber: Subscriber;
  User: User;
}
