### LIST ###

GET {{BASE_URL}}/list HTTP/1.1
Cookie: {{$dotenv COOKIE}}

###
POST {{BASE_URL}}/list HTTP/1.1
content-type: application/json
Cookie: {{$dotenv COOKIE}}

{
  "title": "tutu",
  "pseudonym": "titi"
}

###

GET {{BASE_URL}}/list/67a1b3ec-7d38-4d38-a9a2-1f440890f142 HTTP/1.1
Cookie: {{$dotenv COOKIE}}

### ITEM ###

GET {{BASE_URL}}/list/67a1b3ec-7d38-4d38-a9a2-1f440890f142/items HTTP/1.1
Cookie: {{$dotenv COOKIE}}

###

POST {{BASE_URL}}/list/67a1b3ec-7d38-4d38-a9a2-1f440890f142/items HTTP/1.1
Content-Type: application/json
Cookie: {{$dotenv COOKIE}}

{
  "listId": "67a1b3ec-7d38-4d38-a9a2-1f440890f142",
  "name": "string"
}

###

GET {{BASE_URL}}/item/c672deea-c922-4fb4-b6ce-831980a8481a HTTP/1.1
