### VARIABLES

@listId = 1e26baaf-2981-44d3-b57d-24f62c93638d
@itemId = 3904dac4-7e9d-47ed-b89f-876b36a086c6

### LIST ###

GET {{BASE_URL}}/list HTTP/1.1
Cookie: {{$dotenv COOKIE}}

###
POST {{BASE_URL}}/list HTTP/1.1
content-type: application/json
Cookie: {{$dotenv COOKIE}}

{
  "title": "tutu",
  "pseudonym": "titi"
}

###

GET {{BASE_URL}}/list/{{listId}} HTTP/1.1
Cookie: {{$dotenv COOKIE}}

### ITEM ###

###
GET {{BASE_URL}}/list/{{listId}}/items HTTP/1.1
Cookie: {{$dotenv COOKIE}}

###
POST {{BASE_URL}}/list/{{listId}}/items HTTP/1.1
Content-Type: application/json
Cookie: {{$dotenv COOKIE}}

{
  "name": "string"
}

###
PATCH  {{BASE_URL}}/list/{{listId}}/items/{{itemId}} HTTP/1.1
Content-Type: application/json
Cookie: {{$dotenv COOKIE}}

{
  "isInCart": true
}

###
DELETE  {{BASE_URL}}/list/{{listId}}/items/{{itemId}} HTTP/1.1
Cookie: {{$dotenv COOKIE}}

###

GET {{BASE_URL}}/items/{{itemId}} HTTP/1.1
