### LIST ###

GET {{BASE_URL}}/list?authorId=c9a2553e-3d77-4c07-931a-b1b3a074aa61 HTTP/1.1

###

POST {{BASE_URL}}/list HTTP/1.1
content-type: application/json

{
  "authorId": "c9a2553e-3d77-4c07-931a-b1b3a074aa61",
  "title": "string"
}

###

GET {{BASE_URL}}/list/a347a2d7-c40a-4c19-9c6c-f8c84144cd1c HTTP/1.1


### ITEM ###

GET {{BASE_URL}}/item?listId=e2a0798f-051b-405b-9ee2-161fbda39986 HTTP/1.1

###

POST {{BASE_URL}}/item HTTP/1.1
content-type: application/json

{
  "listId": "e2a0798f-051b-405b-9ee2-161fbda39986",
  "name": "string"
}

###

GET {{BASE_URL}}/item/2db40a46-9604-485c-b448-4f36a26cae51 HTTP/1.1
